#!/usr/bin/env python3


class Program:
    def __init__(self, name, weight, childnames=None):
        self.name = name
        self.weight = weight
        self.childnames = childnames


def first(programs):
    children = [x for program in programs if program.childnames for x in program.childnames]
    fathers = {program.name: program for program in programs if program.name not in children}
    assert len(fathers) == 1
    for father in fathers.values():
        return father


def second(programs):
    directory = {program.name: program for program in programs}
    fathers = {child: program for program in programs if program.childnames for child in program.childnames}
    weights = {}

    # funzione ricorsiva che calcola il peso di un elemento
    def get_weight(name):
        if name in weights:
            return weights[name]

        program = directory[name]
        w = program.weight
        if program.childnames:
            for n in program.childnames:
                w += get_weight(n)
        weights[name] = w
        return w

    def get_wrong(program):
        if program.childnames is None:
            return None

        # cerco il figlio con peso diverso dagli altri
        child_ws = {}
        for child in program.childnames:
            weight = get_weight(child)
            if weight not in child_ws:
                child_ws[weight] = [child]
            else:
                child_ws[weight].append(child)

        # se tutti i figli pesano lo stesso allora questo sotto albero non ha errori
        if len(child_ws) == 1:
            return None

        # dovrei avere i figli in 2 insiemi: quello sbagliato e tutti gli altri
        assert len(child_ws) == 2

        # recupero il valore dei figli giusti e il figlio sbagliato
        w_right = [c for c in child_ws.items() if len(c[1]) > 1][0][0]
        wrong_entry = [c for c in child_ws.items() if len(c[1]) == 1][0]
        w_wrong = wrong_entry[0]
        wrong_child = directory[wrong_entry[1][0]]

        # verifico ricorsivamente se il figlio errato ha a sua volta figli errati
        wrong_rec = get_wrong(wrong_child)
        if wrong_rec is not None:
            return wrong_rec
        # se no mi fermo
        return wrong_child.weight + w_right - w_wrong

    p = programs[0]
    while True:
        r = get_wrong(p)
        if r is not None:
            return r
        p = fathers[p.name]


if __name__ == '__main__':

    data = (
        Program('uwzmqi', 57),
        Program('emlzcpy', 106, ('pwmoihf', 'sdwnkb')),
        Program('oevnzwt', 90),
        Program('imjhra', 23),
        Program('uuimn', 299),
        Program('xzpov', 55),
        Program('kynja', 73),
        Program('kggcnt', 43),
        Program('qdxpkx', 67),
        Program('wubltb', 276, ('udcok', 'pihpjbp', 'hiifqwb')),
        Program('anifo', 10),
        Program('zxdpmwl', 57),
        Program('tkdmopp', 44),
        Program('kdsbbcf', 193, ('huyizg', 'evofb')),
        Program('pxfpf', 235),
        Program('mjftixu', 131, ('kwzsj', 'rspilzk', 'amtxw')),
        Program('dbtoizo', 73),
        Program('fdqmg', 124, ('kggcnt', 'dzekyo')),
        Program('egvfxip', 23),
        Program('mpijek', 63),
        Program('kkoitqr', 70),
        Program('jgwvyp', 29, ('hoagrj', 'swefql')),
        Program('guipj', 25, ('sauwet', 'graedp', 'jdvya', 'bmlwb', 'eidmza', 'kmnmx')),
        Program('ayuhvb', 216, ('bemhni', 'gvpac')),
        Program('unmxfe', 91),
        Program('miwfyq', 96),
        Program('loofhh', 31),
        Program('liczn', 12),
        Program('urvunmn', 63, ('ddsmt', 'oablvt')),
        Program('jxdqhu', 60),
        Program('pvqfa', 174, ('pftmymi', 'vmrdwe')),
        Program('xrabl', 82, ('ivyarjy', 'lhxinfd')),
        Program('rfvtfs', 93),
        Program('qkrirn', 129, ('ceztn', 'tqjmaxi', 'lwroef')),
        Program('epnny', 85, ('xltlyvw', 'ctkjip')),
        Program('hlzyncx', 85),
        Program('fyxdfod', 82),
        Program('bawgh', 7),
        Program('sxpqvwv', 358, ('oziwd', 'rreoxyc', 'qntqokn', 'acibw')),
        Program('nogbp', 119, ('psvkj', 'djyks')),
        Program('mgdhu', 15, ('cfcbhku', 'fltdrlc')),
        Program('nsvan', 1749, ('ahracx', 'dvoul', 'ecxayrz')),
        Program('gefrwix', 99, ('sovfoi', 'vdqpuon', 'ghtdnrx')),
        Program('hfrtlx', 57),
        Program('kyhace', 12),
        Program('gbcfg', 277, ('pzbgmxx', 'lysysqu', 'urvunmn', 'yiohbo', 'hqjlgre')),
        Program('uhwsavi', 57),
        Program('fyynsgp', 6),
        Program('wqobawc', 67),
        Program('agjdl', 61),
        Program('tkureky', 247),
        Program('czalivu', 28),
        Program('wykyl', 64),
        Program('wqtbny', 49),
        Program('wnhkac', 18),
        Program('fuhbamv', 81),
        Program('wqudy', 238, ('dpkdpj', 'jmmticn', 'kpotsk', 'qtntw')),
        Program('latvu', 35),
        Program('inpjzmh', 23),
        Program('orawnkw', 195, ('bsqlkiy', 'fhhzvwj')),
        Program('kwzsj', 40),
        Program('ymfwoto', 50),
        Program('kckucu', 152, ('mnoaa', 'infll')),
        Program('fwlme', 6),
        Program('xlyxjyx', 302, ('lewizr', 'duxfof', 'uqazvo', 'mzbwym')),
        Program('aksgboa', 93),
        Program('rxxqpi', 920, ('gwwphk', 'xaskpny')),
        Program('gqqgsz', 49),
        Program('rlbdave', 27),
        Program('fuunnks', 42, ('cstnc', 'dyxmvo', 'kwtszff', 'ittpbzy')),
        Program('bhcwhrf', 88),
        Program('ppigbow', 84),
        Program('bbzhhk', 70, ('bjrfinh', 'lissl')),
        Program('hsael', 60),
        Program('tcpdvk', 33),
        Program('yvbgs', 286, ('byaaoab', 'kebefwy', 'wpxxz')),
        Program('utjtx', 8, ('rzlkr', 'ntfvgoj', 'qmvpgee')),
        Program('kdcyull', 48),
        Program('ldakuz', 45),
        Program('lcfpcst', 92),
        Program('ufnpup', 102, ('cewmc', 'uwzmqi')),
        Program('eavfy', 87),
        Program('lufgbo', 60),
        Program('sncjicb', 102, ('xslucv', 'jbpvtf', 'gfltww')),
        Program('lydjsu', 65),
        Program('aclnw', 210),
        Program('fqdtzfy', 221, ('zwfly', 'bidasc', 'mjfhodb')),
        Program('wavbwew', 80),
        Program('sqwfq', 59),
        Program('yeicqcy', 46),
        Program('chzrjqp', 90),
        Program('fhabfp', 59),
        Program('wbijkw', 19, ('zzdbn', 'pqxef', 'ikzqhu', 'dyqgl')),
        Program('gbhlxb', 75),
        Program('zpimcy', 83),
        Program('zmjzmyq', 35),
        Program('pagsex', 45),
        Program('onsjs', 197),
        Program('gqiczm', 61, ('gwsceo', 'ucocdl', 'hdqow', 'fjqccm', 'oxvqjeh')),
        Program('hmdqubz', 16, ('juzol', 'txote', 'kynja')),
        Program('lzikkl', 330, ('cdrjh', 'lwbcn')),
        Program('haadpw', 65),
        Program('eeluucp', 62, ('pxsmani', 'qdmop')),
        Program('nnsogp', 60),
        Program('nezhs', 94),
        Program('fqrwf', 88, ('hujzcku', 'tkdmopp', 'ckgmjsg')),
        Program('zoszls', 70),
        Program('uzlgko', 56, ('loyjp', 'wwnkoz')),
        Program('uqazvo', 39),
        Program('sphktgz', 12),
        Program('sikpe', 48),
        Program('rsjmc', 53),
        Program('htyvy', 17),
        Program('ylluriq', 129, ('pawmnl', 'uhmnltu')),
        Program('mrsxl', 18),
        Program('gbkubnt', 45),
        Program('xdvwjb', 70),
        Program('jguhhsb', 9),
        Program('mfyivv', 84),
        Program('etsxvmj', 896, ('enlfaa', 'ymnichj', 'tuefd', 'zhkmnxk', 'vcllnn')),
        Program('cougztw', 27),
        Program('ewifyk', 25, ('sxino', 'vgwxuan')),
        Program('vwtxaci', 78, ('nnkpuhp', 'haadpw')),
        Program('vwqof', 64),
        Program('cewmc', 57),
        Program('haztq', 48),
        Program('wxyhyh', 43),
        Program('dyxmvo', 107, ('tnham', 'jsdvowc')),
        Program('zhcmvvm', 90),
        Program('zdrwxqt', 89),
        Program('bluacvc', 26),
        Program('yxfysz', 418, ('cfmcrf', 'ixbsb', 'kafyh', 'zouqjoo')),
        Program('hiifqwb', 14),
        Program('knsphtv', 74),
        Program('xrwnzgz', 21),
        Program('xtbqb', 82, ('bydmdru', 'awfnh')),
        Program('zngystc', 140, ('gszlkf', 'inkfmx')),
        Program('gtktonk', 92),
        Program('ukkph', 17),
        Program('fzowmer', 22),
        Program('gumpsin', 34),
        Program('rynlaj', 292),
        Program('wjhgb', 48, ('icoic', 'hwhgi')),
        Program('ndvns', 24),
        Program('cawzw', 81),
        Program('kyphnel', 51),
        Program('uawyee', 22),
        Program('mzftrlb', 70),
        Program('xfxsxh', 71),
        Program('wzlonwk', 65),
        Program('inkfmx', 30),
        Program('vkkds', 207, ('pvhdt', 'fshoj', 'dsuonma', 'vuazmuj')),
        Program('wdwgd', 80),
        Program('licby', 79),
        Program('ytlpe', 77),
        Program('usddqi', 170, ('fgokr', 'mdznc', 'psynxr')),
        Program('ychaa', 47),
        Program('ztuswk', 7),
        Program('rtchnfd', 162, ('eptve', 'lejuo')),
        Program('bymrwvc', 67),
        Program('xqusi', 22, ('jdbmary', 'flrdpaj', 'iwysxj', 'tooduon')),
        Program('gyivxga', 26, ('cldaf', 'lqgvx')),
        Program('eptve', 37),
        Program('aflaj', 35),
        Program('ghnldf', 35),
        Program('oldfs', 34),
        Program('bkdxl', 85),
        Program('qsiqu', 114, ('efvvtgo', 'hcfgf', 'fgayln', 'xzkzoq', 'isuevmr', 'xqyyni', 'rjfqyz')),
        Program('abjrozg', 189, ('dlcep', 'rhwfl')),
        Program('fjemwxf', 69, ('ofxdo', 'jjkns', 'mwvihj', 'vrhke')),
        Program('zuapfco', 40),
        Program('tqcwn', 50),
        Program('ouycck', 1843, ('lmliqa', 'txtnweq')),
        Program('hkelse', 71),
        Program('wifvw', 68, ('cpoxc', 'btlczl', 'dqzsblu')),
        Program('cxfvbz', 807, ('vazst', 'evquf', 'pvcpmx')),
        Program('quxtc', 142, ('tcpdvk', 'npwrqsm')),
        Program('fltdrlc', 90),
        Program('fivaym', 45),
        Program('jdvro', 43, ('wkkqsy', 'wdwgd')),
        Program('qinwdk', 178, ('liueudh', 'zgtsnwk')),
        Program('zautz', 48),
        Program('flmeo', 338, ('auocy', 'uqkhzxt')),
        Program('zziuivt', 78),
        Program('iooqbyk', 1558, ('fuhbamv', 'dqrsxx')),
        Program('vumxuur', 99),
        Program('awfnh', 60),
        Program('woeabie', 18),
        Program('xtqnalt', 19),
        Program('xedlv', 67),
        Program('jatrdb', 229, ('njnyoek', 'ctvhcv', 'qsgjk')),
        Program('axjkbq', 188, ('hgoruv', 'iimyku')),
        Program('hmenje', 183, ('npefyxi', 'fwoyu', 'acueoez')),
        Program('zxwmd', 96),
        Program('zapbrn', 421, ('szzhp', 'jsvwb')),
        Program('tmwvxgi', 179, ('egvfxip', 'gohxocn', 'wgvlq')),
        Program('fkagr', 32),
        Program('wppgjkw', 187, ('hlmdgp', 'usglf')),
        Program('wajnp', 54),
        Program('hbgeak', 92),
        Program('rnbvott', 157, ('kaekzo', 'hbozym')),
        Program('haurusk', 170, ('kxgrtg', 'ythbw')),
        Program('ylpvre', 48),
        Program('zmuit', 131, ('vrzrsz', 'uawyee', 'jbxllu')),
        Program('mnoaa', 59),
        Program('zttpfsd', 20),
        Program('solmej', 193, ('wnhkac', 'gkjafru', 'cmfwb')),
        Program('lkzdum', 33),
        Program('vhpjrh', 64),
        Program('sqwejs', 47),
        Program('xxufma', 17),
        Program('eshjt', 10),
        Program('vrzrsz', 22),
        Program('pvhdt', 23),
        Program('dtqyhj', 96),
        Program('htmrm', 85),
        Program('tbsmz', 70),
        Program('hezjirm', 54),
        Program('cozhzk', 62, ('fkagr', 'dqyaco')),
        Program('jcrmny', 70),
        Program('zpadu', 96),
        Program('lfszf', 50),
        Program('vpnfkw', 80, ('ewzvs', 'jbitbzb')),
        Program('rphgr', 895, ('gkfymj', 'rtchnfd', 'gtyfx', 'ujdhkyw')),
        Program('bmlwb', 481),
        Program('mzaxe', 52, ('itzntrm', 'wqtbny', 'jyhddhe', 'zgatapc')),
        Program('qxzhq', 180, ('ezjqb', 'kiceppo', 'zkiotrm', 'gqqgsz')),
        Program('bkfxvy', 1563, ('bkvuz', 'dbtoizo')),
        Program('utaxgw', 57, ('bupugpv', 'gnqxls', 'rnvenxi')),
        Program('vcuizl', 119, ('maklk', 'bxyvuvc')),
        Program('ydbzo', 57),
        Program('lhagpts', 737, ('utjtx', 'bcyipmu', 'vcuizl')),
        Program('dkbycez', 131, ('vagyecy', 'fvzfdr')),
        Program('kdyuwjh', 92),
        Program('udcok', 14),
        Program('xssia', 80),
        Program('hrzvmel', 34),
        Program('dupdsj', 81, ('hgsiz', 'yeicqcy', 'fncsm')),
        Program('gseohkk', 29),
        Program('dllffsl', 54),
        Program('ixbsb', 104, ('gjbikl', 'cogziqp', 'gdibw')),
        Program('pqxpguz', 22, ('tnpzf', 'zaxds', 'jvocm', 'eeluucp', 'zenvqu', 'ytqwzv')),
        Program('abfkpur', 651, ('ppeumu', 'yuvpdk', 'kzimilx', 'wbwyvyu', 'dkwbhuk')),
        Program('khbth', 270),
        Program('vpvab', 76, ('evgvano', 'ibfbn', 'xovrzf', 'qzbet')),
        Program('iwotig', 64),
        Program('nomlh', 74),
        Program('oicxl', 27),
        Program('gqjhcw', 5),
        Program('cmfwb', 18),
        Program('assqm', 23),
        Program('tlyncze', 36),
        Program('pqkzpq', 35, ('gjpcufw', 'ocmac', 'hohsf', 'qdtdbl')),
        Program('zfxzq', 58),
        Program('vhlon', 80),
        Program('yiohbo', 49, ('kwaqrgu', 'nezhs')),
        Program('tymahpb', 87, ('ladkvis', 'rlrcvv', 'fciadzu', 'xpigis', 'kckucu', 'kdrswra', 'khbth')),
        Program('vcmntc', 99),
        Program('beigkn', 86),
        Program('pxzoq', 16, ('mdimlja', 'hrufxbf', 'ufzrg')),
        Program('wuwag', 65),
        Program('jdvya', 385, ('zautz', 'haztq')),
        Program('jbxllu', 22),
        Program('ashtupo', 6),
        Program('xgdyhva', 893, ('tkureky', 'solmej', 'yucxy')),
        Program('tooduon', 92),
        Program('decdq', 43),
        Program('ukhyz', 95, ('ilnlkpv', 'bhzuzbt', 'agevvkl', 'byrfacr')),
        Program('pgscbge', 77),
        Program('vdsjf', 22),
        Program('zqdoieb', 53),
        Program('sgtarpx', 33),
        Program('yhiby', 100, ('tzljrvn', 'ckezp')),
        Program('wdxfr', 55),
        Program('owxgj', 37),
        Program('uhmnltu', 91),
        Program('lsbzpu', 6),
        Program('ciwxuch', 96),
        Program('qskbft', 200),
        Program('gwwphk', 79),
        Program('kbarp', 60),
        Program('ygzas', 55, ('ztyqti', 'nxapqfk')),
        Program('shifzsw', 54),
        Program('huytmw', 37, ('tsdfcgo', 'uqfbsti')),
        Program('atwtz', 58),
        Program('ivcqfao', 117, ('zqdoieb', 'bnmnak')),
        Program('wifwhkq', 80),
        Program('ghtdnrx', 1120, ('jcyxjwa', 'ftuvvv', 'nogbp')),
        Program('ztsajt', 128, ('grvqyf', 'yxsvp')),
        Program('odmlf', 60),
        Program('hocfv', 70),
        Program('xegshds', 53, ('upqkbq', 'hsdkmdv', 'ggxgmci', 'owjvny', 'gqiczm')),
        Program('efulo', 213, ('lzcikn', 'tihjcht')),
        Program('jjkns', 93),
        Program('fedhzki', 61),
        Program('qtntw', 294),
        Program('airlbu', 71),
        Program('rzlkr', 97),
        Program('ogujo', 49),
        Program('jylgvd', 165),
        Program('immcgrm', 47),
        Program('hohsf', 54),
        Program('knzffuc', 11),
        Program('pwamvw', 830, ('nvyaeal', 'tptcl', 'bbloz')),
        Program('nifptxs', 90, ('zapbrn', 'vhxgbd', 'hmenje', 'hlzape', 'ugaxscf', 'fjemwxf', 'arnbvk')),
        Program('psvkj', 81),
        Program('acsqtk', 128, ('ykcivtj', 'bhcwhrf')),
        Program('ehgpqe', 27),
        Program('knxtlig', 57, ('lhqhx', 'alkysnc')),
        Program('sxino', 50),
        Program('hwhgi', 86),
        Program('glpwie', 88, ('tzqux', 'uhwsavi', 'hfrtlx')),
        Program('mrkknr', 34),
        Program('juxcxo', 96),
        Program('pxpeniz', 41),
        Program('buztc', 76),
        Program('ewhzc', 60),
        Program('bqpycy', 253, ('snjfup', 'assqm')),
        Program('oynlkiy', 25),
        Program('inful', 168, ('knzffuc', 'ldgldpx')),
        Program('sybsbk', 27),
        Program('towdptl', 54),
        Program('yujhec', 30, ('qkzgb', 'nmwrqbx', 'dktkg', 'rnbvott', 'etingr')),
        Program('nidvi', 193, ('wjwit', 'dbuxj', 'rhpfhuc', 'ehyygbi')),
        Program('ttkqf', 85),
        Program('iumsv', 51),
        Program('ijvrlpz', 95),
        Program('qqjvdh', 76),
        Program('mwznhh', 17),
        Program('ybwcod', 63),
        Program('yulcus', 24),
        Program('bcswm', 96),
        Program('lfjpkw', 216),
        Program('mjfhodb', 18),
        Program('dbuxj', 20),
        Program('ehyygbi', 20),
        Program('lgdbaig', 4976, ('lplhe', 'sznyfy', 'tjrecaq')),
        Program('odtgv', 92),
        Program('falrf', 97, ('zttpfsd', 'zfaog', 'sdezdnz')),
        Program('wyjnxf', 12, ('bxipuq', 'ibosof')),
        Program('icdptj', 42, ('onlnhb', 'ibqenc')),
        Program('lysysqu', 237),
        Program('vltkp', 33),
        Program('fwjufh', 62),
        Program('uqkhzxt', 60),
        Program('nbdfits', 57),
        Program('mtsju', 42, ('tzevrtu', 'wflxu')),
        Program('uxeyxk', 88, ('ctmob', 'miwfyq', 'dtqyhj')),
        Program('krrxx', 27),
        Program('tzevrtu', 74),
        Program('tjmeqt', 50, ('sinrdj', 'bbrsdwl')),
        Program('itzntrm', 49),
        Program('ehjpn', 291, ('opbaea', 'kvxtl')),
        Program('zayqjx', 95, ('henlezn', 'vhpjrh')),
        Program('cvzsvf', 15),
        Program('mmlsnw', 63),
        Program('agwpt', 84),
        Program('crfmd', 70),
        Program('jjpnqsk', 29),
        Program('otrlqy', 56, ('hzbcp', 'qtcwngh')),
        Program('smkcc', 147, ('yalqeoe', 'uzjoy')),
        Program('ztylsq', 32),
        Program('dvzoq', 17),
        Program('fyuitn', 46, ('iumsv', 'fzmwc')),
        Program('zkiotrm', 49),
        Program('ebhzgav', 13, ('afooq', 'vihjl', 'xxoqrj', 'ipblpmy')),
        Program('wgtmwjd', 682, ('lsoto', 'abqknn', 'uzlgko')),
        Program('kniivab', 9, ('bymrwvc', 'aylzrt')),
        Program('oxrpu', 63),
        Program('rsvcn', 84),
        Program('hgbvgnn', 96),
        Program('udlyr', 227),
        Program('ktaso', 28),
        Program('lmliqa', 67),
        Program('rcpscka', 117, ('eduizfz', 'sholtl')),
        Program('lzvpq', 40),
        Program('sixlpmr', 310, ('ttrvo', 'onsjs', 'ppujydt', 'zmuit', 'dfzbuxo')),
        Program('acibw', 8),
        Program('ftpwtol', 98, ('sstby', 'wduscx')),
        Program('pcfotkv', 23, ('cszltz', 'pqdoti')),
        Program('eknyvq', 97),
        Program('svxpx', 66),
        Program('nhyhkq', 68),
        Program('ttrvo', 123, ('evpfdj', 'icdyfw')),
        Program('hlbhkkr', 80),
        Program('bpuiaqr', 96),
        Program('azykbk', 80),
        Program('mnslyf', 6, ('ouagp', 'wyjnxf', 'jxtzkel', 'vwtxaci', 'quxtc', 'yhiby', 'mgwiq')),
        Program('yfngcvd', 59),
        Program('vfbhl', 92),
        Program('fhcrud', 62),
        Program('ggxgmci', 66063, ('nsvan', 'qcbfbfz', 'anygv', 'gefrwix', 'kkeafw', 'jepbpw')),
        Program('dlcep', 74),
        Program('aylzrt', 67),
        Program('ghxwug', 84),
        Program('auqfj', 8),
        Program('kdajj', 40),
        Program('wjjzh', 96),
        Program('njnyoek', 21),
        Program('lejuo', 37),
        Program('abeinmv', 961, ('tlfklor', 'izqbvna', 'sxpqvwv', 'foqjjt', 'xqusi')),
        Program('bkvaj', 119, ('ktaso', 'ufqlean', 'czalivu')),
        Program('npwrqsm', 33),
        Program('ysvbz', 192, ('ekirg', 'lzvpq')),
        Program('unhnq', 5580, ('rvkalxi', 'kabbsvt', 'jwptb')),
        Program('hqjlgre', 47, ('jxxgurr', 'wvysxc')),
        Program('kpotsk', 294),
        Program('nwand', 344, ('vjtbtv', 'epnny', 'zdagr')),
        Program('xbxqoh', 40),
        Program('ispeb', 30),
        Program('lznlhjd', 33, ('qqjvdh', 'ribswz', 'ndebha', 'vsojq')),
        Program('zlrboun', 55),
        Program('ofxdo', 93),
        Program('oxezpz', 34),
        Program('uqfbsti', 73),
        Program('zjljate', 228, ('fzowmer', 'pcmgq')),
        Program('kbxvke', 195),
        Program('uaxomk', 87),
        Program('udawli', 6, ('eiliwle', 'ijvrlpz')),
        Program('fnefss', 348, ('qrtruk', 'ztsajt', 'aclnw')),
        Program('hbampcd', 10),
        Program('czgws', 57),
        Program('anygv', 3678, ('tghfe', 'ybzqi', 'fabacam')),
        Program('qfxwzis', 47),
        Program('ullsjlc', 99),
        Program('yjarolt', 69),
        Program('cfefqhk', 84),
        Program('wflxu', 74),
        Program('icroy', 52),
        Program('ngkjtk', 47),
        Program('oqsdfwt', 43),
        Program('gswcnfo', 93, ('gwnou', 'xedlv')),
        Program('mdznc', 19),
        Program('zrdjlz', 90),
        Program('btlczl', 205, ('sjoxehw', 'ucrqw')),
        Program('xxyttn', 228, ('dayjxl', 'melthx')),
        Program('qrunwtc', 208, ('rzyuyv', 'gjisc', 'zrqzlvd', 'sqwtiaf', 'kgnuc', 'ufnpup', 'lfjpkw')),
        Program('hocvke', 105, ('xzpov', 'btkih', 'kgijqnz')),
        Program('luswe', 7),
        Program('whqrugy', 77),
        Program('ikkatj', 76),
        Program('hvdafm', 590, ('gglig', 'nuorc', 'ioyesxg')),
        Program('kyjjz', 210),
        Program('aqtgibg', 84),
        Program('byrfacr', 93),
        Program('tooqbdo', 130, ('uaxsa', 'mcdpv', 'ccqsq')),
        Program('zbthq', 88),
        Program('sboslk', 27),
        Program('mwvihj', 93),
        Program('ythbw', 61),
        Program('kgnuc', 76, ('iuzfnx', 'kylauj')),
        Program('xdnrao', 194, ('wptxs', 'pdbtp')),
        Program('nszphks', 60),
        Program('huyizg', 24),
        Program('ujapot', 76),
        Program('uycyz', 2625, ('zzjwnh', 'ncirziy', 'icdptj')),
        Program('xuzskid', 54),
        Program('xcvbgr', 63),
        Program('macpvga', 239, ('fdqmg', 'hyqrffw', 'rfytg', 'idnhoqh', 'dchobfa', 'kyjjz', 'aqahah')),
        Program('afrpf', 29, ('ybbuy', 'uifanza')),
        Program('klqmcsw', 185, ('zvzdrp', 'luswe')),
        Program('euglphc', 165, ('jkyljso', 'abharn')),
        Program('heiejhm', 48, ('ndyceo', 'nvoys')),
        Program('iulkkfp', 112, ('pkwzp', 'cdzlq')),
        Program('ucrqw', 73),
        Program('ivzps', 58),
        Program('lyhgmwz', 12),
        Program('ehwko', 41),
        Program('hasbi', 124),
        Program('pawmnl', 91),
        Program('kbtogma', 96),
        Program('dwwabne', 6),
        Program('wjwit', 20),
        Program('dktkg', 232, ('ztuswk', 'iadezq', 'lhlyb')),
        Program('iimyku', 59),
        Program('nlzohm', 74),
        Program('owgrt', 6, ('zpimcy', 'xconx')),
        Program('nyfdcz', 61, ('zrdjlz', 'oevnzwt')),
        Program('crihz', 75),
        Program('vehan', 188),
        Program('ucocdl', 11321, ('sixlpmr', 'yujhec', 'uryldo', 'bgltopb', 'tpreug', 'gwwjmo', 'pwamvw')),
        Program('urhawb', 43),
        Program('ztyqti', 71),
        Program('akmyzla', 5),
        Program('hdtmmh', 61),
        Program('vckxof', 56, ('qpjgrr', 'lwejw')),
        Program('ctvhcv', 21),
        Program('jdltlbx', 92),
        Program('yxsvp', 41),
        Program('xltlyvw', 87),
        Program('fatxilu', 17),
        Program('jljurl', 14),
        Program('wfold', 83, ('affnbx', 'fhcrud', 'gcfqnlw', 'fwjufh')),
        Program('mlavfvc', 304),
        Program('mhwqim', 70),
        Program('nemomq', 62, ('jatrdb', 'nzrhtgr', 'ngyxxm', 'wnnnvgn', 'emlzcpy', 'haurusk', 'rynlaj')),
        Program('jdbmary', 92),
        Program('icrilh', 47, ('yolrh', 'cglbn')),
        Program('ybzqi', 395, ('pcfotkv', 'ewifyk', 'uredmot')),
        Program('qvcpu', 5),
        Program('qzbet', 255, ('miunk', 'horfum')),
        Program('ckvji', 42),
        Program('jpcurr', 9),
        Program('stjxh', 59),
        Program('kucnmn', 50, ('incbyp', 'ogujo')),
        Program('vikstpo', 80),
        Program('sdezdnz', 20),
        Program('uticq', 47),
        Program('yynji', 85),
        Program('svnqa', 313, ('nthqzh', 'uekit', 'hopiqm')),
        Program('xmufp', 1476, ('cozhzk', 'xvjkwcd', 'yzjmm', 'jzsmrz', 'zuzkw')),
        Program('emdehy', 42),
        Program('usixdl', 84),
        Program('kgqhmx', 27),
        Program('wjnibfh', 12),
        Program('bvwdckm', 47),
        Program('icoic', 86),
        Program('aicos', 78),
        Program('kabbsvt', 1459, ('rwtva', 'wykyl')),
        Program('vuhehz', 589, ('kdsmyax', 'tooqbdo', 'zizsy')),
        Program('lwbcn', 64),
        Program('owjvny', 68748, ('lgdbaig', 'yskay', 'uvftw')),
        Program('moxxiw', 480, ('apyhkb', 'uakqow', 'tutfkbo', 'zmiyzin', 'hgwupie', 'thtnmkb')),
        Program('miunk', 78),
        Program('tjrecaq', 5, ('dzxkea', 'fsckdb', 'dreryps', 'svnqa', 'qfegd')),
        Program('twnon', 66, ('ciwxuch', 'zpadu')),
        Program('fciadzu', 152, ('rmnfq', 'tnxxb')),
        Program('pwmoihf', 93),
        Program('vsbbr', 61),
        Program('apyhkb', 163, ('ixvot', 'dllffsl')),
        Program('dkwbhuk', 1778, ('wavbwew', 'hlbhkkr')),
        Program('gnqxls', 36),
        Program('dlglddh', 98),
        Program('tlfklor', 190, ('bwnvvei', 'thwgxk', 'thcth', 'gvphwwi')),
        Program('pwyspt', 240),
        Program('eynrs', 4953, ('gtvuq', 'vidgimw', 'fnefss', 'clmkbr', 'yxfysz', 'latvopy')),
        Program('ntfvgoj', 97),
        Program('msxnd', 45),
        Program('atwsafs', 245),
        Program('incbyp', 49),
        Program('ktiuc', 1175, ('mzaxe', 'xxyttn', 'tmwvxgi', 'azcuz', 'szkgky', 'beaubot', 'ffvahj')),
        Program('hikmxhb', 6),
        Program('ctmob', 96),
        Program('zmiyzin', 94, ('ryrig', 'sqwfq', 'mbpgrbi')),
        Program('gjauauy', 12),
        Program('asymmuf', 33, ('bwsbj', 'tfiynwo', 'zideon', 'xvkcms', 'jezdog', 'twnon', 'raloti')),
        Program('aoscisa', 12, ('mnyokhx', 'ppigbow', 'eubqww')),
        Program('jbitbzb', 54),
        Program('wwnkoz', 62),
        Program('picati', 50),
        Program('kmnmx', 481),
        Program('lmdsuz', 34),
        Program('nqohnyo', 99),
        Program('rcvol', 76),
        Program('ccqsq', 27),
        Program('bsxjp', 70, ('xcvbgr', 'gdidwas', 'hrhcwn')),
        Program('uakqow', 237, ('advexy', 'zkvrxb')),
        Program('eckgtt', 234, ('sofrfdv', 'nxygf', 'dbcrmjt')),
        Program('azcuz', 64, ('vetib', 'jirva')),
        Program('hegyu', 282, ('mfmrv', 'zwqpx', 'fyynsgp', 'hikmxhb')),
        Program('ppbvdzh', 47),
        Program('snjfup', 23),
        Program('yjlzh', 23),
        Program('qcako', 11),
        Program('lplhe', 1375, ('qrklawm', 'avytp', 'fqrwf')),
        Program('gtyfx', 110, ('vgvfksg', 'mmlsnw')),
        Program('jsdvowc', 76),
        Program('beaubot', 118, ('rscnige', 'dzjwel')),
        Program('wgvlq', 23),
        Program('gjisc', 192, ('liczn', 'lyhgmwz')),
        Program('jdqmr', 10),
        Program('fjouck', 19),
        Program('xreip', 84),
        Program('ooeypdy', 134, ('kgqhmx', 'vrvzkc')),
        Program('beiih', 2781, ('wuwag', 'xbhexk')),
        Program('nroory', 31),
        Program('hswdm', 45),
        Program('kexrse', 40),
        Program('ahracx', 1289, ('mhgdq', 'homcnz')),
        Program('aksev', 153, ('oqctx', 'cvzsvf')),
        Program('hmzal', 155, ('hsael', 'wltyw')),
        Program('cldaf', 97),
        Program('iscnnvh', 606, ('fzzyjt', 'xtbqb', 'vyzhqx', 'owtdq')),
        Program('ibosof', 98),
        Program('lhkoebz', 67, ('jnenlog', 'jblnqb')),
        Program('slnoqn', 21),
        Program('ulhmjq', 34),
        Program('noqbv', 8),
        Program('xeppuz', 7),
        Program('fxpic', 304),
        Program('gktepby', 64),
        Program('gjkbf', 67),
        Program('qaugj', 61),
        Program('bbloz', 51, ('icroy', 'rshqkfx')),
        Program('pjiicj', 67),
        Program('ucqpz', 39, ('dlglddh', 'tvhui')),
        Program('rwgpcs', 57),
        Program('uzxovd', 33),
        Program('jqougaa', 59),
        Program('vrhke', 93),
        Program('kkeafw', 1602, ('gbcfg', 'uodmc', 'mnslyf')),
        Program('dcpqyp', 6, ('soxzrwm', 'zxbirr')),
        Program('ceztn', 37),
        Program('zwfly', 18),
        Program('yfriw', 59, ('xdvwjb', 'crfmd')),
        Program('gefbk', 139, ('ivzps', 'atwtz')),
        Program('dpkdpj', 126, ('mfyivv', 'aqtgibg')),
        Program('xpgzcxc', 71),
        Program('rymvvbq', 118, ('qjtldq', 'bawgh')),
        Program('bkpxd', 20),
        Program('tqjmaxi', 37),
        Program('phqyeg', 90),
        Program('xnzhkrn', 54),
        Program('niydyxq', 33),
        Program('upqkbq', 26244, ('dfnak', 'szsny', 'ehkrs', 'eynrs', 'cbpsyx', 'bbixr', 'zsckv')),
        Program('zcrgoy', 17),
        Program('zuphhfa', 199, ('ospcnv', 'pkagrvq')),
        Program('snhlzkk', 428, ('iriyw', 'qdlcvk', 'mhium')),
        Program('qtcwngh', 67),
        Program('jirva', 92),
        Program('nyqju', 66, ('nszphks', 'kbarp', 'guivwse', 'nnsogp')),
        Program('zdjxp', 716, ('hhjdf', 'woiqeq', 'wfold')),
        Program('schym', 20, ('fgyndgv', 'hlqed')),
        Program('ngyxxm', 96, ('viqhzr', 'yylvwtf')),
        Program('woiqeq', 149, ('jslpd', 'pfjvzzw')),
        Program('sthyxh', 235),
        Program('xbhexk', 65),
        Program('wnnnvgn', 152, ('suqxa', 'wmhjbm')),
        Program('xzixh', 71, ('wdnjs', 'hlzyncx')),
        Program('hwqhsc', 235, ('akmyzla', 'tlekuus')),
        Program('bidasc', 18),
        Program('pzbgmxx', 156, ('vsevm', 'dwztnh', 'sybsbk')),
        Program('ckjdqr', 49),
        Program('qdtdbl', 54),
        Program('dvoul', 816, ('yfriw', 'klqmcsw', 'ueepet')),
        Program('jkyljso', 51),
        Program('ugqjxlt', 43),
        Program('uazvt', 57),
        Program('qovrrvg', 172, ('eboizv', 'rrqfy')),
        Program('wgvxebc', 62),
        Program('iwysxj', 92),
        Program('gmtzu', 30),
        Program('rwtva', 64),
        Program('uulig', 24, ('cqifjd', 'abjrozg', 'lgurkym', 'lznlhjd', 'lskrih')),
        Program('nefive', 168, ('opkjkav', 'kyphnel')),
        Program('qsgjk', 21),
        Program('kgpymt', 18),
        Program('avytp', 154, ('mdbixwm', 'mshht')),
        Program('yskay', 47, ('asymmuf', 'gnjkpwf', 'tlmnwl', 'iyekup', 'rphgr', 'mfohmwu')),
        Program('mmyiwt', 61),
        Program('wfilxtb', 50),
        Program('iibjdbp', 76),
        Program('amtxw', 40),
        Program('ndyceo', 86),
        Program('vbqsm', 250, ('jdqmr', 'hbampcd')),
        Program('ttstqws', 38),
        Program('ybbuy', 87),
        Program('bfrmpr', 101, ('dsjirbh', 'latvu')),
        Program('vagyecy', 52),
        Program('rwlchj', 73),
        Program('vdqpuon', 868, ('pykcpw', 'yioxr', 'lcgym', 'wbijkw', 'dupdsj')),
        Program('zegoosj', 36),
        Program('emcstpe', 71),
        Program('pykcpw', 168, ('bdkmsdy', 'mwznhh', 'zcrgoy')),
        Program('ymnichj', 909, ('jfhpd', 'xvedp', 'phswa', 'udawli', 'tjmeqt')),
        Program('wlibbwd', 5, ('nogjxu', 'bapvb', 'azykbk')),
        Program('bncsnst', 12),
        Program('uxbnnor', 76),
        Program('zbodhfq', 56),
        Program('qhezs', 93),
        Program('drhmhn', 18),
        Program('hcfgf', 197, ('tpfcmlm', 'xxxauxt', 'plcxnz')),
        Program('cbomeum', 35),
        Program('qpjgrr', 66),
        Program('dsjirbh', 35),
        Program('lkoagx', 58),
        Program('szsny', 5431, ('yvbgs', 'lcepfsw', 'exfeog', 'rxxqpi', 'fuunnks')),
        Program('ytlzs', 251, ('xnzhkrn', 'hezjirm', 'xuzskid', 'mwdqdbu')),
        Program('dzxkea', 322, ('cwevfy', 'mepeg', 'bvnfacp', 'tygpx')),
        Program('xikuc', 10),
        Program('rmnfq', 59),
        Program('qfaubqr', 82),
        Program('sauwet', 445, ('bsieig', 'mrsxl')),
        Program('pdzfg', 134, ('qfxwzis', 'ppbvdzh', 'rzwkjvu', 'sqwejs')),
        Program('quryyds', 78, ('tfshhr', 'wdxfr')),
        Program('jvmuid', 62),
        Program('cpwfem', 93),
        Program('wratzd', 22),
        Program('fhdkp', 232, ('sbhcx', 'kdcyull', 'sikpe')),
        Program('agevvkl', 93),
        Program('xadsoxv', 71, ('whqrugy', 'fmlyuv', 'yerfxa')),
        Program('gvpac', 51),
        Program('ipsfv', 211, ('bkpxd', 'xivvpur')),
        Program('zprquyv', 97, ('vrnxiui', 'htmrm')),
        Program('akobg', 1607, ('vcsdacf', 'udfmh', 'ambgac')),
        Program('phxtzgu', 78, ('exfffna', 'ewhzc', 'lufgbo', 'odmlf')),
        Program('rreoxyc', 8),
        Program('jmmticn', 24, ('chzrjqp', 'zhcmvvm', 'phqyeg')),
        Program('woxpci', 80),
        Program('cvchqoz', 24),
        Program('qxnuj', 70),
        Program('tpfcmlm', 20),
        Program('hewjj', 263, ('dwwabne', 'iwhazt')),
        Program('adxox', 79),
        Program('bxyvuvc', 90),
        Program('opbaea', 26),
        Program('xcbliim', 404, ('wonyy', 'drhmhn', 'kgpymt')),
        Program('kzimilx', 328, ('qmttkg', 'hpobvlt', 'pdzfg', 'zkborz', 'sbanx')),
        Program('mtvoxu', 54),
        Program('qfggzok', 67),
        Program('vxtfjhq', 23),
        Program('hixeb', 80),
        Program('bkvuz', 73),
        Program('npozpo', 98),
        Program('uqhnekk', 17),
        Program('rhpfhuc', 20),
        Program('ribswz', 76),
        Program('mnyokhx', 84),
        Program('oleuqo', 43),
        Program('usbjyly', 907, ('mjftixu', 'vldursw', 'ipsfv', 'pqkzpq', 'fkdauwn')),
        Program('nkbtsr', 19),
        Program('szzhp', 10),
        Program('hgwbjzo', 83, ('pnhxqna', 'zxwmd')),
        Program('bubhosg', 45),
        Program('lxxkjb', 45),
        Program('yolrh', 14),
        Program('cdzlq', 96),
        Program('mbpgrbi', 59),
        Program('lqvrx', 85),
        Program('mmaqp', 159, ('fsdlnh', 'ypmvfz')),
        Program('ekirg', 40),
        Program('mdimlja', 36),
        Program('cxynfb', 183, ('wcqsimj', 'kwxpb', 'jprkymy', 'yjlzh')),
        Program('kgijqnz', 55),
        Program('bapvb', 80),
        Program('oqctx', 15),
        Program('bemhni', 51),
        Program('lcgym', 199, ('anifo', 'eshjt')),
        Program('hopiqm', 31),
        Program('ujdhkyw', 136, ('yccqn', 'wfilxtb')),
        Program('ygbphkw', 2416, ('eujnekp', 'utaxgw', 'jylgvd')),
        Program('occtbf', 11),
        Program('vhdke', 7, ('wqtbb', 'buztc', 'trzjoi', 'brubv')),
        Program('hpobvlt', 186, ('lmdsuz', 'gumpsin', 'xpzzkdb', 'oxezpz')),
        Program('bdprpzc', 38),
        Program('xcuid', 26),
        Program('txayxeg', 146, ('ngkjtk', 'uticq')),
        Program('ftuvvv', 89, ('juxcxo', 'onmghy')),
        Program('vgysxct', 103, ('cygpuh', 'svxpx')),
        Program('nxapqfk', 71),
        Program('kylauj', 70),
        Program('amyymhg', 52),
        Program('jjpco', 92),
        Program('mgmoe', 45),
        Program('sinrdj', 73),
        Program('rzclv', 91),
        Program('ahcjog', 59, ('yhhob', 'rvbbn', 'cawzw')),
        Program('saqcb', 64),
        Program('cfmcrf', 126, ('phmqb', 'xeppuz')),
        Program('uluavyz', 311),
        Program('rzyuyv', 182, ('uqhnekk', 'yqpivvl')),
        Program('ckezp', 54),
        Program('ljihfp', 71),
        Program('plcxnz', 20),
        Program('uguqde', 18),
        Program('scdvmta', 40),
        Program('sofrfdv', 28),
        Program('sahfob', 87),
        Program('lzcikn', 30),
        Program('gdidwas', 63),
        Program('xqyyni', 227, ('sjiaux', 'dwkkssy')),
        Program('yoibok', 50),
        Program('wjgdz', 54),
        Program('uifanza', 87),
        Program('ufzrg', 36),
        Program('kwxpb', 23),
        Program('vmrdwe', 13),
        Program('yucxy', 65, ('mpedpht', 'jhzoyme')),
        Program('xuzvwcg', 23, ('bluacvc', 'xcuid')),
        Program('wrbtgkb', 45),
        Program('abqknn', 142, ('kialkdr', 'xtqnalt')),
        Program('dklrle', 46),
        Program('lhqbgck', 632, ('ykcxtea', 'zjljate', 'ysvbz', 'qovrrvg')),
        Program('smzpa', 114, ('jugwirf', 'ttborca', 'tmuuyka')),
        Program('fwoyu', 86),
        Program('dgkhq', 64),
        Program('tvhui', 98),
        Program('clyht', 10),
        Program('sspem', 80),
        Program('pgpvnb', 39),
        Program('zkborz', 322),
        Program('liueudh', 63),
        Program('myrlvj', 63),
        Program('cszltz', 51),
        Program('ambgac', 34),
        Program('pwznn', 120, ('cougztw', 'krrxx')),
        Program('iwhazt', 6),
        Program('hgoruv', 59),
        Program('gglig', 156, ('saqcb', 'mubenp', 'vwqof')),
        Program('bwnvvei', 50),
        Program('ezjgtbp', 71),
        Program('xzkzoq', 73, ('gtktonk', 'odtgv')),
        Program('qkzgb', 219, ('ukkph', 'zrsya')),
        Program('cphgovc', 269, ('nnqghfo', 'ohjvf')),
        Program('bdkmsdy', 17),
        Program('hzbcp', 67),
        Program('btkih', 55),
        Program('ejyho', 96),
        Program('ecagt', 7),
        Program('vhxgbd', 267, ('lkoagx', 'vrjfn', 'zfxzq')),
        Program('estka', 47),
        Program('tihjcht', 30),
        Program('tcaemi', 171),
        Program('bnmnak', 53),
        Program('jtendcr', 85),
        Program('uekit', 31),
        Program('jbpvbc', 168, ('caukzx', 'pjiicj')),
        Program('pdbtp', 91),
        Program('gjpcufw', 54),
        Program('bvnfacp', 21),
        Program('dqzsblu', 91, ('wzlonwk', 'ywxkr', 'iggqobg', 'lydjsu')),
        Program('fjekad', 48),
        Program('juzol', 73),
        Program('dfzbuxo', 17, ('fdrki', 'ufmlfmj', 'jxdqhu')),
        Program('dombfx', 57, ('oxrpu', 'ybwcod')),
        Program('eidmza', 481),
        Program('advexy', 17),
        Program('ddleaoo', 71),
        Program('bcyipmu', 229, ('aflaj', 'cbomeum')),
        Program('rsttknu', 97, ('bsxjp', 'bmzeddf', 'ndwvmg', 'glpwie', 'exbgy')),
        Program('tnham', 76),
        Program('zideon', 236, ('occtbf', 'hmltq')),
        Program('gfltww', 51),
        Program('eduizfz', 79),
        Program('fsdlnh', 54),
        Program('jugwirf', 51),
        Program('yylvwtf', 98),
        Program('npefyxi', 86),
        Program('gszlkf', 30),
        Program('wptxs', 91),
        Program('amntev', 61),
        Program('hlqed', 76),
        Program('rvbbn', 81),
        Program('sygyji', 6),
        Program('wcqsimj', 23),
        Program('fjqccm', 14455, ('tymahpb', 'ouycck', 'ehazo')),
        Program('gcfqnlw', 62),
        Program('nnbokwt', 194, ('mngea', 'hcajnu')),
        Program('bxipuq', 98),
        Program('izqbvna', 250, ('zoszls', 'kkoitqr')),
        Program('zxbirr', 83),
        Program('nkipkdo', 72),
        Program('yuvpdk', 1257, ('gswcnfo', 'vceutc', 'kahwlj')),
        Program('eiliwle', 95),
        Program('ohjvf', 99),
        Program('cvkmmqc', 54),
        Program('cdvscgo', 44, ('tjmyc', 'phxtzgu', 'ayuhvb', 'eckgtt', 'wubltb')),
        Program('trzjoi', 76),
        Program('zzdbn', 50),
        Program('wonyy', 18),
        Program('woxmeo', 56),
        Program('enohjb', 206, ('bkdxl', 'ttkqf')),
        Program('sznyfy', 1243, ('xkfxnp', 'aoscisa', 'bbzhhk')),
        Program('phbapzv', 50),
        Program('gkfymj', 92, ('fbvhl', 'nkipkdo')),
        Program('hmltq', 11),
        Program('kafyh', 36, ('eincbt', 'amyymhg')),
        Program('pbkmeod', 78, ('estka', 'ychaa')),
        Program('fgyndgv', 76),
        Program('kunhp', 19, ('rqpbivd', 'kdyuwjh')),
        Program('vruhp', 227, ('woxpci', 'hixeb', 'sspem')),
        Program('jirnr', 24),
        Program('kaekzo', 48),
        Program('dsuonma', 23),
        Program('xdxhzm', 893, ('sncjicb', 'mmvhi', 'brchwcm', 'gefbk')),
        Program('bxpfs', 92),
        Program('qdzbmhn', 1640, ('xrabl', 'pwznn', 'dvzguq')),
        Program('aplke', 19),
        Program('veuqzjh', 25),
        Program('tpreug', 377, ('axjkbq', 'hegyu', 'nyqju')),
        Program('fpmvb', 17),
        Program('hlmdgp', 78),
        Program('wbgwke', 19),
        Program('dzjumb', 43),
        Program('clmkbr', 482, ('hasbi', 'pxzoq', 'ecfquya', 'coezio')),
        Program('affnbx', 62),
        Program('ignblg', 123, ('txeege', 'owxgj')),
        Program('ehqlqj', 40),
        Program('vulynlf', 18),
        Program('tghfe', 89, ('usddqi', 'zuphhfa', 'rjzbhh')),
        Program('mdbixwm', 33),
        Program('fdrki', 60),
        Program('ggxhzhd', 10, ('masck', 'amntev')),
        Program('obejsk', 99),
        Program('eubqww', 84),
        Program('auocy', 60),
        Program('pqxef', 50),
        Program('lhlyb', 7),
        Program('tfiynwo', 174, ('emdehy', 'zgtzox')),
        Program('jezdog', 58, ('wvxvu', 'picati', 'tnisesh', 'yoibok')),
        Program('zizsy', 89, ('hdtmmh', 'mmyiwt')),
        Program('ufmlfmj', 60),
        Program('maklk', 90),
        Program('oxvqjeh', 17638, ('xscyb', 'wzjsbdm', 'lzikkl', 'xlyxjyx', 'flmeo', 'xcbliim')),
        Program('mmvhi', 113, ('xpgzcxc', 'ddleaoo')),
        Program('yalqeoe', 38),
        Program('ecfquya', 32, ('vlfpib', 'dklrle')),
        Program('sagihe', 940, ('bicpqwm', 'dyfptec', 'kbxvke', 'mgdhu')),
        Program('kiceppo', 49),
        Program('tnpzf', 114, ('ewrcce', 'jqougaa')),
        Program('vceutc', 29, ('nqohnyo', 'vumxuur')),
        Program('uzdzkal', 32),
        Program('csotuo', 34),
        Program('xlufw', 93),
        Program('hdqow', 10132, ('uulig', 'macpvga', 'bkfxvy', 'zdjxp', 'akobg', 'vjboadc')),
        Program('rfqquyg', 92),
        Program('sqwtiaf', 30, ('aksgboa', 'qhezs')),
        Program('lamrqdl', 59),
        Program('ittpbzy', 101, ('jrkbskn', 'tqxfj')),
        Program('vjboadc', 1160, ('dombfx', 'aksev', 'huytmw')),
        Program('iriyw', 193, ('vxzgkqa', 'fjouck')),
        Program('hiftfo', 88),
        Program('bsqlkiy', 20),
        Program('hzkeiu', 16),
        Program('arnbvk', 329, ('zbodhfq', 'woxmeo')),
        Program('pxsmani', 85),
        Program('jfapwfu', 28, ('qhsptw', 'oqsdfwt', 'rsaitjm', 'decdq')),
        Program('jrkbskn', 79),
        Program('zouqjoo', 140),
        Program('wduscx', 86),
        Program('vetib', 92),
        Program('qtfroa', 112, ('pxpeniz', 'ehwko', 'ujfmq')),
        Program('wgqnrc', 30),
        Program('nvyaeal', 29, ('mpijek', 'myrlvj')),
        Program('vsevm', 27),
        Program('cdxwbv', 23),
        Program('tzqux', 57),
        Program('qkqgwsl', 19),
        Program('ykcivtj', 88),
        Program('tsdfcgo', 73),
        Program('aqahah', 68, ('airlbu', 'tgvqqn')),
        Program('jddzj', 11),
        Program('zuzkw', 16, ('sqfue', 'zlrboun')),
        Program('rdizbi', 30),
        Program('lhxinfd', 46),
        Program('sjiaux', 15),
        Program('zfaog', 20),
        Program('tgsdks', 18),
        Program('dreryps', 38, ('rfqquyg', 'jdltlbx', 'obqactw', 'hbgeak')),
        Program('xkfxnp', 72, ('ejyho', 'hgbvgnn')),
        Program('qrtruk', 63, ('ckjdqr', 'dtmhqm', 'tzdntld')),
        Program('mgwiq', 16, ('wjjzh', 'kbtogma')),
        Program('sjoxehw', 73),
        Program('jbpvtf', 51),
        Program('gjtpl', 48),
        Program('hrhcwn', 63),
        Program('igkso', 40, ('tqfzh', 'gbhlxb')),
        Program('cygpuh', 66),
        Program('fckfbce', 105, ('jtendcr', 'fcutr')),
        Program('yerfxa', 77),
        Program('vjtbtv', 77, ('unmxfe', 'rzclv')),
        Program('ppujydt', 23, ('pujhjf', 'lvwwxt')),
        Program('qmvpgee', 97),
        Program('kdrswra', 102, ('xreip', 'ghxwug')),
        Program('oablvt', 87),
        Program('latvopy', 38, ('smmnc', 'quryyds', 'vyptki', 'hgchigs', 'vckxof')),
        Program('uaxsa', 27),
        Program('lissl', 97),
        Program('xovrzf', 331, ('ehqlqj', 'scdvmta')),
        Program('homcnz', 62),
        Program('crsjegg', 21, ('iooqbyk', 'qrunwtc', 'bumibye', 'lhqbgck', 'sagihe', 'vpvab')),
        Program('pkagrvq', 14),
        Program('thcth', 50),
        Program('nogjxu', 80),
        Program('hhjdf', 207, ('wgvxebc', 'jvmuid')),
        Program('ipblpmy', 46),
        Program('qmttkg', 94, ('ohohls', 'zxdpmwl', 'czgws', 'ydbzo')),
        Program('qjtldq', 7),
        Program('iggqobg', 65),
        Program('hhfgih', 152, ('wratzd', 'vdsjf', 'tbynt', 'hlzzxi')),
        Program('xvjkwcd', 40, ('oleuqo', 'urhawb')),
        Program('fabacam', 305, ('dlcxjg', 'dlactl', 'falrf')),
        Program('xvrgg', 77),
        Program('fshoj', 23),
        Program('uredmot', 55, ('zmjzmyq', 'ghnldf')),
        Program('psynxr', 19),
        Program('dtiprc', 61),
        Program('pevdihc', 135, ('rbmoj', 'hiftfo')),
        Program('jxtzkel', 132, ('bdprpzc', 'ptfeyky')),
        Program('uvftw', 1277, ('hvdafm', 'xgdyhva', 'vvndbk', 'gwkfb', 'cdvscgo', 'lhagpts')),
        Program('jvocm', 114, ('lamrqdl', 'stjxh')),
        Program('zgtzox', 42),
        Program('fzmwc', 51),
        Program('aopwj', 77),
        Program('vgeln', 89),
        Program('nvwknv', 47),
        Program('vrvzkc', 27),
        Program('sholtl', 79),
        Program('guivwse', 60),
        Program('gjbikl', 12),
        Program('kdsmyax', 51, ('vhlon', 'vikstpo')),
        Program('dyqgl', 50),
        Program('uqjsosg', 67),
        Program('kahwlj', 79, ('nlzohm', 'nomlh')),
        Program('lqgvx', 97),
        Program('sstby', 86),
        Program('sgcmty', 77),
        Program('hgchigs', 34, ('djktoc', 'aopwj')),
        Program('ouagp', 24, ('lcfpcst', 'bxpfs')),
        Program('tsahe', 106, ('gjkbf', 'uqjsosg')),
        Program('psjbb', 86),
        Program('vrjfn', 58),
        Program('rjzbhh', 91, ('sarppfb', 'nhyhkq')),
        Program('melthx', 10),
        Program('nuorc', 40, ('ytlpe', 'fvhfru', 'xvrgg', 'kbdbe')),
        Program('mubenp', 64),
        Program('mqtxqmz', 12, ('lqvrx', 'chczyg')),
        Program('ypmvfz', 54),
        Program('txote', 73),
        Program('vxzgkqa', 19),
        Program('bbrsdwl', 73),
        Program('xconx', 83),
        Program('enlfaa', 479, ('djquz', 'sthyxh', 'hkuay', 'hmdqubz', 'qxccjtw', 'vgysxct')),
        Program('wbwyvyu', 13, ('hmzal', 'fckfbce', 'fqdtzfy', 'hgwbjzo', 'hewjj', 'rcpscka', 'cxynfb')),
        Program('cvrph', 145, ('dbdrdzo', 'acdahz')),
        Program('izsgfu', 64),
        Program('jcexcl', 18),
        Program('oacoxb', 1336, ('msazzkr', 'jbpvht')),
        Program('acdahz', 83),
        Program('afooq', 46),
        Program('fkdauwn', 187, ('aynknet', 'uzdzkal')),
        Program('mpedpht', 91),
        Program('lcepfsw', 218, ('schym', 'pbkmeod', 'ntodfz', 'owgrt', 'dcpqyp')),
        Program('xscyb', 458),
        Program('pujhjf', 87),
        Program('jtankmh', 190),
        Program('pxctb', 71),
        Program('tqfzh', 75),
        Program('jzsmrz', 126),
        Program('nzrhtgr', 150, ('ezjgtbp', 'xfxsxh')),
        Program('tnxfqf', 34),
        Program('djquz', 211, ('fwlme', 'lsbzpu', 'ashtupo', 'gbauyfh')),
        Program('jyhddhe', 49),
        Program('wdnjs', 85),
        Program('byaaoab', 186, ('ikhsv', 'pgpvnb')),
        Program('bumibye', 997, ('xzixh', 'kdsbbcf', 'nyfdcz')),
        Program('frffchv', 33),
        Program('cogziqp', 12),
        Program('brchwcm', 27, ('uxbnnor', 'iibjdbp', 'qupaz')),
        Program('fbvvzp', 304),
        Program('tnisesh', 50),
        Program('henlezn', 64),
        Program('kbdbe', 77),
        Program('vojpfo', 43),
        Program('psxqu', 61),
        Program('fvzfdr', 52),
        Program('rvkalxi', 77, ('vlzbp', 'jbpvbc', 'muvvvu', 'xadsoxv', 'ahcjog')),
        Program('abharn', 51),
        Program('gegdmus', 42),
        Program('hfdjtw', 43),
        Program('zoqmn', 54),
        Program('vgwxuan', 50),
        Program('pjukxu', 76, ('ikkatj', 'ujapot', 'rcvol')),
        Program('oziwd', 8),
        Program('evgvano', 411),
        Program('evquf', 195),
        Program('gkjafru', 18),
        Program('ygwxr', 144, ('ylpvre', 'cabbtti')),
        Program('dniumoe', 83, ('wajnp', 'mtvoxu', 'towdptl', 'kmiax')),
        Program('tlekuus', 5),
        Program('mrchmw', 43, ('xssia', 'wifwhkq')),
        Program('ueepet', 113, ('ugoetwf', 'hfdjtw')),
        Program('znzsgk', 98),
        Program('cabbtti', 48),
        Program('cbpsyx', 1290, ('nifptxs', 'oxzecjg', 'uycyz')),
        Program('ulqnjx', 18),
        Program('ezjqb', 49),
        Program('xvkcms', 212, ('vxtfjhq', 'imjhra')),
        Program('kxgrtg', 61),
        Program('hxtbym', 50),
        Program('pqdoti', 51),
        Program('lizkruo', 15),
        Program('zzjwnh', 130, ('ehgpqe', 'oicxl')),
        Program('mzbwym', 39),
        Program('nkixmeh', 32),
        Program('xxxauxt', 20),
        Program('caukzx', 67),
        Program('zenvqu', 124, ('sboslk', 'fwudfax', 'rlbdave', 'onqnmbp')),
        Program('ivyarjy', 46),
        Program('ldgldpx', 11),
        Program('grvqyf', 41),
        Program('hlzzxi', 22),
        Program('jsvwb', 10),
        Program('cglbn', 14),
        Program('swefql', 99),
        Program('zgtsnwk', 63),
        Program('hlzape', 373, ('fatxilu', 'htyvy', 'fpmvb', 'xxufma')),
        Program('lqylns', 82, ('inful', 'igkso', 'mtsju', 'otrlqy', 'jtankmh', 'vorviq')),
        Program('iouzha', 161, ('slnoqn', 'gmmkqp')),
        Program('kwtszff', 119, ('bkfqmqn', 'tbsmz')),
        Program('rqpbivd', 92),
        Program('bupugpv', 36),
        Program('zaxds', 66, ('ygywjq', 'pusxipi')),
        Program('onmghy', 96),
        Program('jnenlog', 78),
        Program('sovfoi', 97, ('uluavyz', 'vhdke', 'kuivtq', 'ylluriq', 'cvrph', 'pevdihc')),
        Program('cfcbhku', 90),
        Program('tgvqqn', 71),
        Program('ncirziy', 48, ('ulhmjq', 'zwoqof', 'hrzvmel', 'vrbss')),
        Program('obqactw', 92),
        Program('udfmh', 34),
        Program('hgsiz', 46),
        Program('bicpqwm', 177, ('sygyji', 'bjfou', 'qsche')),
        Program('jslpd', 91),
        Program('pcmgq', 22),
        Program('graedp', 89, ('npozpo', 'znzsgk', 'jxvses', 'teikos')),
        Program('pnhxqna', 96),
        Program('cwwdl', 73),
        Program('msazzkr', 28),
        Program('mngea', 23),
        Program('gohxocn', 23),
        Program('qfqnrvt', 4602, ('ptwedjj', 'xdxhzm', 'qsiqu')),
        Program('rsaitjm', 43),
        Program('lwroef', 37),
        Program('jbpvht', 28),
        Program('wjovhv', 35, ('gokngb', 'vczph', 'phbapzv', 'tqcwn')),
        Program('nsabyg', 99),
        Program('tvbswr', 45),
        Program('fwbly', 134, ('dzjumb', 'ugqjxlt')),
        Program('hrufxbf', 36),
        Program('wltyw', 60),
        Program('ptfeyky', 38),
        Program('jwptb', 1539, ('yulcus', 'ndvns')),
        Program('qxccjtw', 178, ('wbgwke', 'arqqbb', 'qkqgwsl')),
        Program('ewrcce', 59),
        Program('oxzecjg', 2983, ('eknyvq', 'myypsh')),
        Program('dwkkssy', 15),
        Program('gnxiznu', 126, ('nroory', 'loofhh')),
        Program('bejncv', 38),
        Program('qcbfbfz', 2322, ('vuhehz', 'lqylns', 'wgtmwjd')),
        Program('pkwzp', 96),
        Program('owtdq', 103, ('frffchv', 'lkzdum', 'sgtarpx')),
        Program('mdauzot', 240),
        Program('alkysnc', 73),
        Program('gtvuq', 898, ('zuapfco', 'kexrse')),
        Program('eewbbvo', 70),
        Program('jfhpd', 196),
        Program('mshht', 33),
        Program('sbanx', 204, ('fhabfp', 'yfngcvd')),
        Program('pusxipi', 83),
        Program('mwbvrhn', 182),
        Program('fbvhl', 72),
        Program('ulvmck', 1649, ('bfrmpr', 'tcaemi', 'gkvrrq')),
        Program('yproaz', 18),
        Program('bgltopb', 866, ('bpbik', 'kniivab', 'quyasfd')),
        Program('nnkpuhp', 65),
        Program('bhzuzbt', 93),
        Program('tcbrhdi', 87),
        Program('guzycwt', 34),
        Program('jdabb', 61),
        Program('fsckdb', 268, ('yjarolt', 'dewtepm')),
        Program('yfkyv', 45),
        Program('hyqrffw', 146, ('ztylsq', 'nkixmeh')),
        Program('ctkjip', 87),
        Program('vularzu', 93),
        Program('ygywjq', 83),
        Program('xzjcf', 1843, ('mmaqp', 'euglphc', 'smzpa', 'zprquyv')),
        Program('jblnqb', 78),
        Program('dbcrmjt', 28),
        Program('dewtepm', 69),
        Program('zdagr', 249, ('gqjhcw', 'qvcpu')),
        Program('jepbpw', 383, ('tgwmbza', 'wifvw', 'nwand', 'tyjrdme', 'snhlzkk')),
        Program('duxfof', 39),
        Program('tzljrvn', 54),
        Program('smmnc', 20, ('agwpt', 'cfefqhk')),
        Program('vgvfksg', 63),
        Program('ugaxscf', 289, ('vtneuhy', 'bfcab')),
        Program('tbynt', 22),
        Program('hkuay', 121, ('bejncv', 'fpqpmca', 'ttstqws')),
        Program('eujnekp', 7, ('licby', 'adxox')),
        Program('exfeog', 853, ('crihz', 'xuzvwcg', 'icrilh')),
        Program('gmmkqp', 21),
        Program('qfegd', 228, ('vgeln', 'zdrwxqt')),
        Program('lewizr', 39),
        Program('teikos', 98),
        Program('bwsbj', 216, ('xrwnzgz', 'hydfd')),
        Program('frzwdkn', 11),
        Program('fgokr', 19),
        Program('cwevfy', 21),
        Program('dzekyo', 43),
        Program('tmuuyka', 51),
        Program('njppj', 23),
        Program('eboizv', 50),
        Program('gvphwwi', 50),
        Program('vidgimw', 534, ('dsstjf', 'fyuitn', 'kucnmn')),
        Program('wmhjbm', 70),
        Program('zkvrxb', 17),
        Program('gwnou', 67),
        Program('pihpjbp', 14),
        Program('lwejw', 66),
        Program('fmlyuv', 77),
        Program('rtstdkd', 47),
        Program('kmiax', 54),
        Program('vyptki', 98, ('mgmoe', 'msxnd')),
        Program('gwkfb', 1238, ('ggxhzhd', 'rymvvbq', 'wvwiwua')),
        Program('wvwiwua', 108, ('wjnibfh', 'exiwwbx')),
        Program('shilhu', 67),
        Program('bpbik', 97, ('cdxwbv', 'zchxtxj')),
        Program('hssgk', 14),
        Program('hujzcku', 44),
        Program('tjmyc', 258, ('gmtzu', 'rdizbi')),
        Program('vhjfcw', 191, ('yproaz', 'tgsdks')),
        Program('ewzvs', 54),
        Program('qsche', 6),
        Program('rxwtoee', 30),
        Program('muvvvu', 167, ('gbkubnt', 'lxxkjb', 'vjdrrnk')),
        Program('sbhcx', 48),
        Program('vvndbk', 953, ('jgwvyp', 'udlyr', 'vhjfcw')),
        Program('nnqghfo', 99),
        Program('coezio', 70, ('jcexcl', 'woeabie', 'uguqde')),
        Program('zchxtxj', 23),
        Program('rfytg', 142, ('oldfs', 'mrkknr')),
        Program('ndtsa', 7),
        Program('qrklawm', 78, ('emcstpe', 'pxctb')),
        Program('ladkvis', 99, ('nbdfits', 'uazvt', 'rwgpcs')),
        Program('ewiugad', 167, ('uzxovd', 'vltkp', 'niydyxq', 'yxknolf')),
        Program('yioxr', 150, ('njppj', 'inpjzmh', 'nbfpp')),
        Program('exfffna', 60),
        Program('rrqfy', 50),
        Program('sdwnkb', 93),
        Program('rshqkfx', 52),
        Program('fvhfru', 77),
        Program('tutfkbo', 187, ('ckvji', 'gegdmus')),
        Program('vlfpib', 46),
        Program('lsoto', 148, ('fwjnm', 'hzkeiu')),
        Program('ecxayrz', 63, ('wutzd', 'vbqsm', 'nefive', 'ftpwtol', 'hocvke')),
        Program('urexzjf', 187, ('wxyhyh', 'vojpfo')),
        Program('nbfpp', 23),
        Program('rspilzk', 40),
        Program('zgatapc', 49),
        Program('vcsdacf', 34),
        Program('rnvenxi', 36),
        Program('mcdpv', 27),
        Program('oieuzv', 25),
        Program('txtnweq', 67),
        Program('sarppfb', 68),
        Program('wpxxz', 20, ('fedhzki', 'vsbbr', 'psxqu', 'jdabb')),
        Program('usglf', 78),
        Program('ujfmq', 41),
        Program('fpqpmca', 38),
        Program('yxknolf', 33),
        Program('ppeumu', 517, ('mrchmw', 'bkvaj', 'iouzha', 'knxtlig', 'jdvro', 'afrpf', 'kunhp')),
        Program('acueoez', 86),
        Program('foqjjt', 294, ('fjekad', 'gjtpl')),
        Program('dyfptec', 105, ('ispeb', 'wgqnrc', 'rxwtoee')),
        Program('idnhoqh', 70, ('mzftrlb', 'qxnuj')),
        Program('vrnxiui', 85),
        Program('tgwmbza', 1064, ('aplke', 'tqnqxx', 'nkbtsr')),
        Program('mhgdq', 62),
        Program('yccqn', 50),
        Program('bbixr', 4503, ('xmufp', 'moxxiw', 'nemomq')),
        Program('aynknet', 32),
        Program('cdrjh', 64),
        Program('hgwupie', 115, ('aicos', 'zziuivt')),
        Program('fwjnm', 16),
        Program('qhsptw', 43),
        Program('ptwedjj', 33, ('xdnrao', 'enohjb', 'uxeyxk', 'qxzhq', 'fhdkp')),
        Program('jxvses', 98),
        Program('xvedp', 50, ('cwwdl', 'rwlchj')),
        Program('jxxgurr', 95),
        Program('etingr', 217, ('ulqnjx', 'vulynlf')),
        Program('bsieig', 18),
        Program('mhium', 203, ('hssgk', 'jljurl')),
        Program('vlzbp', 286, ('auqfj', 'noqbv')),
        Program('suqxa', 70),
        Program('dlcxjg', 17, ('mhwqim', 'jcrmny')),
        Program('xpigis', 270),
        Program('ehkrs', 11, ('ulvmck', 'dhujegl', 'fngfnuz', 'qdzbmhn', 'usbjyly')),
        Program('xxoqrj', 46),
        Program('rscnige', 65),
        Program('dhujegl', 34, ('mlavfvc', 'fxpic', 'fbvvzp', 'qinwdk', 'acsqtk', 'pjukxu', 'iulkkfp')),
        Program('qgufw', 74),
        Program('cznqutl', 99),
        Program('evpfdj', 37),
        Program('pfjvzzw', 91),
        Program('ffvahj', 47, ('qdxpkx', 'vmvjl', 'qfggzok')),
        Program('yfouoak', 56, ('vfbhl', 'jjpco')),
        Program('qntqokn', 8),
        Program('kebefwy', 246, ('jguhhsb', 'jpcurr')),
        Program('hbozym', 48),
        Program('infll', 59),
        Program('wvysxc', 95),
        Program('ospcnv', 14),
        Program('nvoys', 86),
        Program('efvvtgo', 185, ('zegoosj', 'tlyncze')),
        Program('lhqhx', 73),
        Program('yqpivvl', 17),
        Program('hcajnu', 23),
        Program('tgtjhg', 25),
        Program('viqhzr', 98),
        Program('yygyfi', 155, ('jddzj', 'qcako', 'frzwdkn')),
        Program('yzjmm', 36, ('ldakuz', 'fivaym')),
        Program('kialkdr', 19),
        Program('gdibw', 12),
        Program('rdngdrd', 80),
        Program('lgurkym', 337),
        Program('ddsmt', 87),
        Program('rkdopb', 82, ('todbu', 'sahfob', 'uaxomk')),
        Program('xslucv', 51),
        Program('bfcab', 76),
        Program('gnjkpwf', 947, ('zayqjx', 'smkcc', 'lhkoebz', 'ivcqfao')),
        Program('iadezq', 7),
        Program('ckgmjsg', 44),
        Program('tqxfj', 79),
        Program('nmwrqbx', 55, ('obejsk', 'nsabyg')),
        Program('mepeg', 21),
        Program('iuzfnx', 70),
        Program('bfphqmo', 99),
        Program('myypsh', 97),
        Program('ykcxtea', 86, ('cpwfem', 'vularzu')),
        Program('yhhob', 81),
        Program('fcutr', 85),
        Program('rjfqyz', 71, ('rfvtfs', 'xlufw')),
        Program('ryrig', 59),
        Program('fzzyjt', 202),
        Program('tyjrdme', 321, ('zngystc', 'jfapwfu', 'qskbft', 'pvqfa')),
        Program('ywxkr', 65),
        Program('vjdrrnk', 45),
        Program('tptcl', 61, ('krxpma', 'rtstdkd')),
        Program('tnxxb', 59),
        Program('zrsya', 17),
        Program('jprkymy', 23),
        Program('icdyfw', 37),
        Program('iovan', 1882, ('wppgjkw', 'rkdopb', 'ehjpn')),
        Program('qeijcl', 12),
        Program('izfqx', 47),
        Program('mwdqdbu', 54),
        Program('txeege', 37),
        Program('onqnmbp', 27),
        Program('isuevmr', 221, ('sphktgz', 'gjauauy', 'bncsnst')),
        Program('ohohls', 57),
        Program('kwaqrgu', 94),
        Program('mfmrv', 6),
        Program('dzjwel', 65),
        Program('ibfbn', 75, ('hquuw', 'sreeeqf', 'usixdl', 'rsvcn')),
        Program('uzjoy', 38),
        Program('jhzoyme', 91),
        Program('loyjp', 62),
        Program('vazst', 45, ('ymfwoto', 'hxtbym', 'lfszf')),
        Program('jkhruz', 15),
        Program('ioyesxg', 132, ('wjgdz', 'cvkmmqc', 'shifzsw', 'zoqmn')),
        Program('veyvaoh', 7),
        Program('cpoxc', 217, ('wqobawc', 'shilhu')),
        Program('zvzdrp', 7),
        Program('hydfd', 21),
        Program('tygpx', 21),
        Program('juvwvsn', 53),
        Program('phswa', 176, ('xikuc', 'clyht')),
        Program('fhhzvwj', 20),
        Program('vldursw', 145, ('rsjmc', 'juvwvsn')),
        Program('ocmac', 54),
        Program('dchobfa', 12, ('ullsjlc', 'cznqutl')),
        Program('onlnhb', 71),
        Program('ftolbk', 183, ('pagsex', 'wrbtgkb')),
        Program('flrdpaj', 92),
        Program('vmvjl', 67),
        Program('kqcog', 48, ('bcswm', 'bpuiaqr')),
        Program('cstnc', 79, ('bubhosg', 'tvbswr', 'hswdm', 'yfkyv')),
        Program('vuazmuj', 23),
        Program('eincbt', 52),
        Program('wzjsbdm', 62, ('sytjgl', 'tfuuzgi', 'bfphqmo', 'vcmntc')),
        Program('dvyohbc', 85),
        Program('zwoqof', 34),
        Program('wqtbb', 76),
        Program('gkvrrq', 77, ('izfqx', 'bvwdckm')),
        Program('xivvpur', 20),
        Program('jxzyc', 141, ('nvwknv', 'immcgrm')),
        Program('ufqlean', 28),
        Program('todbu', 87),
        Program('qdmop', 85),
        Program('thtnmkb', 95, ('adjfke', 'zbthq')),
        Program('ikzqhu', 50),
        Program('jcyxjwa', 98, ('agjdl', 'dtiprc', 'qaugj')),
        Program('horfum', 78),
        Program('dayjxl', 10),
        Program('vczph', 50),
        Program('alpas', 17, ('dgkhq', 'izsgfu', 'gktepby', 'iwotig')),
        Program('dqrsxx', 81),
        Program('ixvot', 54),
        Program('hoagrj', 99),
        Program('dwztnh', 27),
        Program('uodmc', 727, ('atwsafs', 'hwqhsc', 'wlibbwd')),
        Program('dqyaco', 32),
        Program('bkfqmqn', 70),
        Program('dlactl', 127, ('jkhruz', 'lizkruo')),
        Program('kuivtq', 311),
        Program('wkkqsy', 80),
        Program('szkgky', 76, ('psjbb', 'beigkn')),
        Program('wutzd', 168, ('guzycwt', 'tnxfqf', 'csotuo')),
        Program('rlrcvv', 128, ('hkelse', 'ljihfp')),
        Program('vtneuhy', 76),
        Program('exbgy', 159, ('veuqzjh', 'oynlkiy', 'oieuzv', 'tgtjhg')),
        Program('bjrfinh', 97),
        Program('hsdkmdv', 50286, ('unhnq', 'crsjegg', 'abfkpur', 'qfqnrvt', 'etsxvmj')),
        Program('masck', 61),
        Program('vrbss', 34),
        Program('ytqwzv', 68, ('qfaubqr', 'fyxdfod')),
        Program('kvxtl', 26),
        Program('ibqenc', 71),
        Program('zsckv', 6579, ('iscnnvh', 'pqxpguz', 'wqudy')),
        Program('splhdhe', 80),
        Program('raloti', 104, ('sgcmty', 'pgscbge')),
        Program('sreeeqf', 84),
        Program('tqnqxx', 19),
        Program('xaskpny', 79),
        Program('gbauyfh', 6),
        Program('exiwwbx', 12),
        Program('phmqb', 7),
        Program('bydmdru', 60),
        Program('zwqpx', 6),
        Program('ehazo', 1097, ('heiejhm', 'fwbly', 'gyivxga', 'wjhgb')),
        Program('zudhbe', 168, ('ndtsa', 'ecagt')),
        Program('fncsm', 46),
        Program('zhkmnxk', 21, ('ytlzs', 'ukhyz', 'cphgovc', 'vruhp')),
        Program('cqifjd', 189, ('knsphtv', 'qgufw')),
        Program('vcllnn', 244, ('dkbycez', 'jxzyc', 'qtfroa', 'ucqpz', 'wjovhv', 'pxfpf', 'orawnkw')),
        Program('arqqbb', 19),
        Program('dsstjf', 100, ('cvchqoz', 'jirnr')),
        Program('bjfou', 6),
        Program('gokngb', 50),
        Program('qupaz', 76),
        Program('opkjkav', 51),
        Program('fgayln', 257),
        Program('jzdtwf', 7),
        Program('dbdrdzo', 83),
        Program('sytjgl', 99),
        Program('nthqzh', 31),
        Program('ndwvmg', 235, ('qeijcl', 'kyhace')),
        Program('gwwjmo', 575, ('mdauzot', 'yfouoak', 'qkrirn')),
        Program('evofb', 24),
        Program('ugoetwf', 43),
        Program('zrqzlvd', 42, ('eavfy', 'tcbrhdi')),
        Program('djyks', 81),
        Program('gwsceo', 9, ('beiih', 'guipj', 'xzjcf', 'ktiuc', 'iovan', 'ygbphkw', 'abeinmv')),
        Program('qdlcvk', 61, ('dvyohbc', 'yynji')),
        Program('lvwwxt', 87),
        Program('fngfnuz', 1222, ('vehan', 'yygyfi', 'vpnfkw', 'gnxiznu', 'ooeypdy')),
        Program('dfnak', 6645, ('cxfvbz', 'oacoxb', 'rsttknu')),
        Program('pftmymi', 13),
        Program('ikhsv', 39),
        Program('quyasfd', 63, ('xbxqoh', 'kdajj')),
        Program('ntodfz', 172),
        Program('krxpma', 47),
        Program('xpzzkdb', 34),
        Program('dtmhqm', 49),
        Program('hquuw', 84),
        Program('tfuuzgi', 99),
        Program('rbmoj', 88),
        Program('tfshhr', 55),
        Program('nxygf', 28),
        Program('wvxvu', 50),
        Program('chczyg', 85),
        Program('djktoc', 77),
        Program('ttborca', 51),
        Program('pvcpmx', 137, ('jjpnqsk', 'gseohkk')),
        Program('fwudfax', 27),
        Program('vyzhqx', 62, ('eewbbvo', 'hocfv')),
        Program('dvzguq', 140, ('ulzcu', 'dvzoq')),
        Program('rhwfl', 74),
        Program('mfohmwu', 344, ('dniumoe', 'uuimn', 'ewiugad', 'vkkds', 'bqpycy')),
        Program('lskrih', 177, ('splhdhe', 'rdngdrd')),
        Program('vihjl', 46),
        Program('adjfke', 88),
        Program('brubv', 76),
        Program('rzwkjvu', 47),
        Program('iyekup', 1248, ('ignblg', 'ebhzgav', 'ygzas')),
        Program('uryldo', 749, ('mqtxqmz', 'mwbvrhn', 'zudhbe')),
        Program('vorviq', 176, ('jzdtwf', 'veyvaoh')),
        Program('vsojq', 76),
        Program('ilnlkpv', 93),
        Program('tzdntld', 49),
        Program('tuefd', 209, ('kqcog', 'hhfgih', 'nnbokwt', 'pwyspt', 'txayxeg', 'tsahe', 'ygwxr')),
        Program('bmzeddf', 259),
        Program('sqfue', 55),
        Program('ndebha', 76),
        Program('ulzcu', 17),
        Program('tlmnwl', 474, ('nidvi', 'alpas', 'urexzjf', 'ftolbk', 'efulo')),
        Program('thwgxk', 50),
        Program('soxzrwm', 83)
    )

    res = first(data)
    print(">>> %s" % res.name)

    res = second(data)
    print(">>> %s" % res)
